# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=200)),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('writer', models.CharField(max_length=200)),
                ('collection', models.CharField(max_length=200)),
                ('cover_loc', models.CharField(max_length=400)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('read_count', models.IntegerField()),
                ('storyfile', models.CharField(max_length=250)),
            ],
        ),
    ]
